# Generated by Django 2.2.6 on 2019-11-23 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_auto_20191121_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='SigninForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=10)),
                ('pwd', models.CharField(max_length=10)),
            ],
        ),
    ]
