# Generated by Django 2.2.6 on 2019-11-23 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_signinform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SigninForm',
            new_name='Signin',
        ),
    ]
